using Newtonsoft.Json.Linq;
using Shouldly;
using Xunit;

namespace PhantasmaPhoenix.Protocol.Tests;

/// <summary>
/// Pins the wallet-side pairing parser and encrypted channel to vectors generated by the TS SDK
/// (link-pairing-vectors.json): URIs built by the dApp must parse to the same material, and
/// frames sealed by the dApp must open to the same envelope JSON.
/// </summary>
public class LinkPairingChannelTests
{
	private static readonly JObject Vectors = JObject.Parse(
		File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "link-pairing-vectors.json")));

	[Fact]
	public void Parses_the_sym_universal_link_pairing_uri_built_by_TS()
	{
		var vector = (JObject)Vectors["pairing"]![0]!;
		var parsed = LinkPairing.Parse((string)vector["uri"]!);

		parsed.Version.ShouldBe(5);
		parsed.Topic.ShouldBe("topic-abc123");
		parsed.Mode.ShouldBe(LinkPairingMode.Sym);
		Convert.ToBase64String(parsed.SymKey!).ShouldBe((string)vector["expect"]!["key"]!);
		parsed.Relay.ShouldBe("link.phantasma.info");
		parsed.CallbackUrl.ShouldBe("https://dapp.example/play");
		parsed.DappName.ShouldBe("Test dApp");
		parsed.DappUrl.ShouldBe("https://dapp.example");
	}

	[Fact]
	public void Parses_the_ecdh_custom_scheme_pairing_uri_built_by_TS()
	{
		var vector = (JObject)Vectors["pairing"]![1]!;
		var parsed = LinkPairing.Parse((string)vector["uri"]!);

		parsed.Topic.ShouldBe("t2");
		parsed.Mode.ShouldBe(LinkPairingMode.Ecdh);
		Convert.ToBase64String(parsed.DappPublicKey!).ShouldBe((string)vector["expect"]!["key"]!);
		parsed.Relay.ShouldBeNull();
		parsed.DappName.ShouldBeNull();
	}

	[Theory]
	[InlineData("https://link.phantasma.info/v5/pair")] // no fragment
	[InlineData("https://link.phantasma.info/v5/pair#v=4&t=x&sk=AA")] // wrong version
	[InlineData("https://link.phantasma.info/v5/pair#v=5&sk=AA")] // no topic
	[InlineData("https://link.phantasma.info/v5/pair#v=5&t=x")] // neither sk nor pk
	[InlineData("https://link.phantasma.info/v5/pair#v=5&t=x&sk=AA&pk=BB")] // both keys
	[InlineData("https://link.phantasma.info/v5/pair#v=5&t=x&sk=AAAA")] // key not 32 bytes
	[InlineData("phantasma://v5/pair#v=5&t=x&pk=%%%")] // malformed key encoding
	public void Rejects_malformed_pairing_uris(string uri)
	{
		Should.Throw<FormatException>(() => LinkPairing.Parse(uri));
	}

	[Fact]
	public void Opens_the_envelope_frame_sealed_by_TS()
	{
		var vector = (JObject)Vectors["envelope"]!;
		var channel = new LinkChannel(Convert.FromBase64String((string)vector["key"]!));

		var ok = channel.TryOpenEnvelope(vector["frame"]!.ToString(Newtonsoft.Json.Formatting.None), out var json);

		ok.ShouldBeTrue();
		json.ShouldBe((string)vector["json"]!);
	}

	[Fact]
	public void Seals_frames_the_channel_itself_can_open_and_rejects_other_keys()
	{
		var key = Convert.FromBase64String((string)Vectors["envelope"]!["key"]!);
		var channel = new LinkChannel(key);
		const string envelope = "{\"plv\":5,\"id\":\"a\",\"result\":{\"ok\":true}}";

		var frame = channel.SealEnvelope(envelope);
		channel.TryOpenEnvelope(frame, out var opened).ShouldBeTrue();
		opened.ShouldBe(envelope);

		var otherKey = (byte[])key.Clone();
		otherKey[0] ^= 0xff;
		new LinkChannel(otherKey).TryOpenEnvelope(frame, out _).ShouldBeFalse();

		channel.TryOpenEnvelope("not json", out _).ShouldBeFalse();
		channel.TryOpenEnvelope("{\"nonce\":\"AA==\",\"ct\":\"AA==\"}", out _).ShouldBeFalse();
	}
}
