using System.Text.Json;
using PhantasmaPhoenix.Cryptography;
using Shouldly;
using Xunit;

namespace PhantasmaPhoenix.Cryptography.Tests;

/// <summary>
/// Pins the C# NaCl implementation to vectors generated by the TS SDK (tweetnacl): the wallet
/// and a dApp must derive identical session keys and produce/open identical frames, or the v5
/// encrypted channel cannot work. Vector file: nacl-interop-vectors.json (TS-generated).
/// </summary>
public class NaClInteropTests
{
	private sealed class SecretBoxVector
	{
		public string key { get; set; } = "";
		public string nonce { get; set; } = "";
		public string ciphertext { get; set; } = "";
		public string plaintext { get; set; } = "";
	}

	private sealed class BoxBeforeVector
	{
		public string aPub { get; set; } = "";
		public string aSec { get; set; } = "";
		public string bPub { get; set; } = "";
		public string bSec { get; set; } = "";
		public string sessionKey { get; set; } = "";
	}

	private sealed class VectorFile
	{
		public List<SecretBoxVector> secretbox { get; set; } = new();
		public List<BoxBeforeVector> box_before { get; set; } = new();
	}

	private static readonly VectorFile Vectors = JsonSerializer.Deserialize<VectorFile>(
		File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "nacl-interop-vectors.json")))!;

	[Fact]
	public void Opens_every_frame_sealed_by_the_TS_implementation()
	{
		Vectors.secretbox.Count.ShouldBe(8);
		foreach (var v in Vectors.secretbox)
		{
			var ok = NaCl.TrySecretBoxOpen(
				Convert.FromBase64String(v.ciphertext),
				Convert.FromBase64String(v.nonce),
				Convert.FromBase64String(v.key),
				out var plaintext);

			ok.ShouldBeTrue();
			Convert.ToBase64String(plaintext).ShouldBe(v.plaintext);
		}
	}

	[Fact]
	public void Seals_to_the_exact_TS_ciphertext_given_the_same_nonce()
	{
		// Encryption is deterministic for a fixed nonce: byte equality proves the whole
		// construction (keystream layout, Poly1305 key, tag placement) matches tweetnacl.
		foreach (var v in Vectors.secretbox)
		{
			var sealedBox = NaCl.SecretBoxSeal(
				Convert.FromBase64String(v.plaintext),
				Convert.FromBase64String(v.nonce),
				Convert.FromBase64String(v.key));

			Convert.ToBase64String(sealedBox).ShouldBe(v.ciphertext);
		}
	}

	[Fact]
	public void Derives_the_same_session_key_as_tweetnacl_box_before()
	{
		Vectors.box_before.Count.ShouldBe(4);
		foreach (var v in Vectors.box_before)
		{
			var fromA = NaCl.DeriveSessionKey(Convert.FromBase64String(v.bPub), Convert.FromBase64String(v.aSec));
			var fromB = NaCl.DeriveSessionKey(Convert.FromBase64String(v.aPub), Convert.FromBase64String(v.bSec));

			Convert.ToBase64String(fromA).ShouldBe(v.sessionKey);
			Convert.ToBase64String(fromB).ShouldBe(v.sessionKey);
		}
	}

	[Fact]
	public void Rejects_tampered_frames()
	{
		var v = Vectors.secretbox.First(x => x.plaintext.Length > 0);
		var key = Convert.FromBase64String(v.key);
		var nonce = Convert.FromBase64String(v.nonce);

		var tamperedBody = Convert.FromBase64String(v.ciphertext);
		tamperedBody[tamperedBody.Length - 1] ^= 0x01;
		NaCl.TrySecretBoxOpen(tamperedBody, nonce, key, out _).ShouldBeFalse();

		var tamperedTag = Convert.FromBase64String(v.ciphertext);
		tamperedTag[0] ^= 0x01;
		NaCl.TrySecretBoxOpen(tamperedTag, nonce, key, out _).ShouldBeFalse();

		var wrongKey = Convert.FromBase64String(v.ciphertext);
		var otherKey = (byte[])key.Clone();
		otherKey[5] ^= 0xff;
		NaCl.TrySecretBoxOpen(wrongKey, nonce, otherKey, out _).ShouldBeFalse();
	}

	[Fact]
	public void Round_trips_with_fresh_keys_and_nonces()
	{
		var key = NaCl.GenerateSessionKey();
		var nonce = NaCl.GenerateNonce();
		var plaintext = new byte[12345];
		new Random(7).NextBytes(plaintext);

		var sealedBox = NaCl.SecretBoxSeal(plaintext, nonce, key);
		NaCl.TrySecretBoxOpen(sealedBox, nonce, key, out var opened).ShouldBeTrue();
		opened.ShouldBe(plaintext);
	}

	[Fact]
	public void Generated_keypairs_agree_on_the_session_key()
	{
		var (alicePub, aliceSec) = NaCl.GenerateKeyPair();
		var (bobPub, bobSec) = NaCl.GenerateKeyPair();

		var aliceView = NaCl.DeriveSessionKey(bobPub, aliceSec);
		var bobView = NaCl.DeriveSessionKey(alicePub, bobSec);

		aliceView.ShouldBe(bobView);
		aliceView.Length.ShouldBe(32);
	}
}
